version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: "gunicorn -w 2 'app:app' -b 0.0.0.0:8000"
